"use client"

import { useState, type ReactNode } from "react"
import { ArrowRight, BarChart3, Bell, Check, ChevronDown, Menu, QrCode, ScanLine, ShieldCheck, X } from "lucide-react"

const features = [
  { icon: QrCode, title: "QR feedback", text: "Give every table a simple link customers can open instantly." },
  { icon: ScanLine, title: "Zero login", text: "No account, phone number, or app. Just scan, rate, and submit." },
  { icon: Bell, title: "Telegram alerts", text: "Get the signal while the customer is still at the table." },
  { icon: BarChart3, title: "Clear analytics", text: "See ratings, comments, and trends without spreadsheets." },
]
const faqs = [
  ["Do customers need an account?", "No. Customers simply scan the QR code and submit feedback anonymously."],
  ["How many tables can I add?", "Unlimited tables on both plans, with a unique QR code for every table."],
  ["How much is Pro?", "Pro costs ৳199/month and includes unlimited feedback plus Telegram alerts."],
  ["Does feedback deo support WhatsApp?", "No. Telegram is the notification channel, keeping alerts focused and simple."],
]

type Modal = "signup" | "login" | "feedback" | null

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [openFaq, setOpenFaq] = useState(0)
  const [modal, setModal] = useState<Modal>(null)
  const [submitted, setSubmitted] = useState(false)
  const close = () => { setModal(null); setSubmitted(false) }
  const openSignup = () => { setMenuOpen(false); setModal("signup") }

  return <main>
    <nav className="container" style={{height:76,display:"flex",alignItems:"center",justifyContent:"space-between"}}>
      <a href="#home" className="brand" style={{fontSize:21,fontWeight:700,textDecoration:"none",color:"var(--ink)"}}>feedback <span style={{color:"var(--green)"}}>deo</span><span style={{color:"var(--green)"}}>.</span></a>
      <div style={{display:"flex",gap:30,alignItems:"center"}} className="desktop-nav"><a href="#how" className="navlink">How it works</a><a href="#features" className="navlink">Features</a><a href="#pricing" className="navlink">Pricing</a><a href="#faq" className="navlink">FAQ</a><button className="login" onClick={()=>setModal("login")}>Log in</button><button className="button dark" onClick={openSignup}>Get started <ArrowRight size={15}/></button></div>
      <button className="mobile-menu" aria-label="Open menu" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button>
    </nav>
    {menuOpen && <div className="mobile-links container"><a href="#how" onClick={()=>setMenuOpen(false)}>How it works</a><a href="#features" onClick={()=>setMenuOpen(false)}>Features</a><a href="#pricing" onClick={()=>setMenuOpen(false)}>Pricing</a><a href="#faq" onClick={()=>setMenuOpen(false)}>FAQ</a><button onClick={()=>{setMenuOpen(false);setModal("login")}}>Log in</button><button className="button dark" onClick={openSignup}>Get started <ArrowRight size={15}/></button></div>}
    <section id="home" className="hero grid-bg"><div className="container hero-grid"><div><div className="eyebrow"><span className="pulse"/> Built for local businesses in Bangladesh</div><h1>Know what your customers <em>really</em> think.</h1><p className="lead">Let customers rate their experience in seconds with a simple QR code. No login. No long forms. Just honest feedback.</p><div className="hero-actions"><button className="button green" onClick={openSignup}>Get started free <ArrowRight size={16}/></button><a className="text-link" href="#how">See how it works <ArrowRight size={16}/></a></div><div className="trust"><div className="avatars"><span>R</span><span>M</span><span>S</span><span>+</span></div><div><div className="star">★★★★★</div><small>Loved by cafés in Dhaka</small></div></div></div><DemoCard onSubmit={()=>setModal("feedback")}/></div></section>
    <section id="how" className="section"><div className="container"><div className="section-heading"><div><p className="kicker">HOW IT WORKS</p><h2>Small moment.<br/><span>Big difference.</span></h2></div><p>Feedback deo makes it easy to hear from the people who matter most — your customers.</p></div><div className="steps"><Step n="01" title="Create your space" text="Sign up and add your restaurant in under two minutes."/><Step n="02" title="Place your QR codes" text="Generate a unique QR for every table and print it."/><Step n="03" title="Listen and improve" text="Customers scan, rate, and you see what to do next."/></div></div></section>
    <section id="features" className="section pale"><div className="container"><div className="section-heading"><div><p className="kicker">MADE FOR THE FLOOR</p><h2>Everything you need.<br/><span>Nothing you don&apos;t.</span></h2></div></div><div className="feature-grid">{features.map(({icon:Icon,title,text})=><div className="feature" key={title}><div className="iconbox"><Icon size={21}/></div><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
    <section id="dashboard" className="section"><div className="container dashboard-wrap"><div><p className="kicker">ONE CLEAR VIEW</p><h2>Your customer&apos;s voice,<br/><span>all in one place.</span></h2><p className="body-copy">Spot patterns, celebrate the good, and fix the small things before they become big things.</p><button className="text-link" onClick={openSignup}>Explore the dashboard <ArrowRight size={16}/></button></div><MiniDashboard/></div></section>
    <section id="pricing" className="pricing section"><div className="container"><div className="center-heading"><p className="kicker">SIMPLE PRICING</p><h2>Start free. Grow when ready.</h2><p>One location, unlimited tables, no surprises.</p></div><div className="plans"><Plan title="Free" price="৳0" text="For getting started" features={["1 location","Unlimited tables & QR codes","50 feedback submissions/month","Dashboard & basic analytics"]} onClick={openSignup}/><Plan pro title="Pro" price="৳199" text="For teams that want the full picture" features={["Everything in Free","Unlimited feedback","Instant Telegram alerts","Advanced analytics & exports"]} onClick={openSignup}/></div></div></section>
    <section id="faq" className="section"><div className="container faq-grid"><div><p className="kicker">QUESTIONS, ANSWERED</p><h2>Good to know.</h2><p className="body-copy">Still curious? We keep things as simple as the product.</p><a className="text-link" href="mailto:hello@feedbackdeo.com">Ask us anything <ArrowRight size={16}/></a></div><div>{faqs.map(([q,a],i)=><div className="faq" key={q}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)}><span>{q}</span><ChevronDown size={18} style={{transform:openFaq===i?"rotate(180deg)":"none"}}/></button>{openFaq===i&&<p>{a}</p>}</div>)}</div></div></section>
    <footer><div className="container footer-row"><a className="brand" href="#home">feedback <span>deo</span>.</a><span>Simple customer feedback for local businesses.</span><div><a href="#features">Features</a><a href="#pricing">Pricing</a><a href="mailto:hello@feedbackdeo.com">Contact</a></div><small>© 2026 feedback deo.</small></div></footer>
    {modal && <Modal title={modal === "feedback" ? "Tell us about your visit" : modal === "login" ? "Welcome back" : "Start collecting better feedback"} close={close}>{submitted ? <div className="success-state"><div className="success-mark">✓</div><h3>{modal === "feedback" ? "Thanks for sharing." : "You&apos;re on the list."}</h3><p>{modal === "feedback" ? "Your feedback helps this business improve." : "We&apos;ll help you set up your first feedback space."}</p><button className="button green full" onClick={close}>Done</button></div> : modal === "feedback" ? <FeedbackForm onSubmit={()=>setSubmitted(true)}/> : <AccessForm mode={modal} onSubmit={()=>setSubmitted(true)}/>}</Modal>}
  </main>
}
function DemoCard({onSubmit}:{onSubmit:()=>void}){return <div className="demo-area"><div className="scan-card soft-shadow"><div className="scan-head"><span className="tiny-brand">feedback <b>deo</b></span><span className="live"><i/> LIVE</span></div><div className="scan-body"><div className="logo-circle">C</div><small>THE COMMONS CAFÉ · DHAKA</small><h3>How was your<br/>experience?</h3><div className="big-stars">★★★★★</div><div className="fake-input">Tell us what you think... <span>optional</span></div><button className="button green full" onClick={onSubmit}>Submit feedback <ArrowRight size={15}/></button><small className="anonymous"><ShieldCheck size={13}/> Anonymous by default</small></div></div><div className="alert-card soft-shadow"><div className="alert-icon"><Bell size={16}/></div><div><small>NEW FEEDBACK · TELEGRAM</small><strong>4/5 <span className="star">★★★★</span></strong><p>“Lovely food, quick service.”</p><small>Table 12 · just now</small></div></div><div className="orb orb-one"/><div className="orb orb-two"/></div>}
function FeedbackForm({onSubmit}:{onSubmit:()=>void}){return <form className="modal-form" onSubmit={(e)=>{e.preventDefault();onSubmit()}}><label>Rating<select required defaultValue=""><option value="" disabled>Choose a rating</option><option>5 - Excellent</option><option>4 - Good</option><option>3 - Average</option><option>2 - Needs work</option><option>1 - Poor</option></select></label><label>Your feedback<textarea placeholder="What should we know?" required /></label><button className="button green full" type="submit">Send feedback <ArrowRight size={15}/></button><small className="anonymous"><ShieldCheck size={13}/> Anonymous by default</small></form>}
function AccessForm({mode,onSubmit}:{mode:"signup"|"login",onSubmit:()=>void}){return <form className="modal-form" onSubmit={(e)=>{e.preventDefault();onSubmit()}}><label>Email address<input type="email" placeholder="you@business.com" required /></label><label>Password<input type="password" placeholder="At least 8 characters" minLength={8} required /></label>{mode === "signup" && <label>Business name<input placeholder="The Commons Café" required /></label>}<button className="button green full" type="submit">{mode === "login" ? "Log in" : "Create free space"} <ArrowRight size={15}/></button><small className="form-note">Demo access is ready. Connect Supabase auth to persist accounts.</small></form>}
function Modal({title,close,children}:{title:string,close:()=>void,children:ReactNode}){return <div className="modal-backdrop" role="presentation" onMouseDown={(e)=>{if(e.target===e.currentTarget)close()}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="modal-close" aria-label="Close" onClick={close}><X/></button><p className="kicker">FEEDBACK DEO</p><h2 id="modal-title">{title}</h2>{children}</div></div>}
function MiniDashboard(){return <div className="mini-dashboard soft-shadow"><div className="mini-top"><div><small>THIS MONTH</small><strong>Customer pulse</strong></div><span className="green-pill">+18.4%</span></div><div className="metric-row"><div><small>Average rating</small><b>4.6 <span className="star">★</span></b></div><div><small>Total feedback</small><b>127</b></div></div><div className="bars"><small>Rating distribution</small>{[["5 stars",72],["4 stars",17],["3 stars",7],["1–2 stars",4]].map(([label,value])=><div className="bar-row" key={label}><span>{label}</span><div><i style={{width:`${value}%`}}/></div><b>{value}%</b></div>)}</div><div className="feedback-note"><div className="star">★★★★★</div><strong>“Great food and very friendly staff.”</strong><small>Table 8 · 2 minutes ago</small></div></div>}
function Step({n,title,text}:{n:string,title:string,text:string}){return <div className="step"><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></div>}
function Plan({title,price,text,features,pro=false,onClick}:{title:string,price:string,text:string,features:string[],pro?:boolean,onClick:()=>void}){return <div className={`plan ${pro?"pro-plan":""}`}>{pro&&<div className="most">MOST POPULAR</div>}<h3>{title}</h3><p>{text}</p><div className="price">{price}<small>/month</small></div><button className={`button ${pro?"green":"outline"} full`} onClick={onClick}>{pro?"Upgrade to Pro":"Start free"} <ArrowRight size={15}/></button><div className="plan-features">{features.map(f=><div key={f}><Check size={16}/>{f}</div>)}</div></div>}

